title: Owen Kim, Whitman College
description: 
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman

url: https://owen-kim3.github.io
baseurl: ""

social_links:
  linkedin: https://www.linkedin.com/in/owenkim03/
