title: Owen Kim, Whitman College '25
description: Showcasing my interests, data analysis project ideas, and past projects I have done.
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman
