title: Owen Kim, Whitman College
description: You can connect with me on [LinkedIn](https://www.linkedin.com/in/owenkim03/) to learn more about my professional background, education, and skills! Welcome to my GitHub page!
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman
